# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:

  chirpstack-gateway-mesh:
    container_name: chirpstack-gateway-mesh
    image: xoseperez/chirpstack-gateway-mesh
    restart: unless-stopped
    privileged: true
    user: "${PUID:-1000}:${PGID:-1000}"
    depends_on:
      - chirpstack-concentratord
    volumes:
      - /tmp:/tmp
    environment:
      - LOGGING_LEVEL=INFO
      - RELAY_BORDER=${RELAY_BORDER:-false}
      - RELAY_SIGNING_KEY=${RELAY_SIGNING_KEY:-00000000000000000000000000000000}
      - RELAY_MAX_HOP_COUNT=${RELAY_MAX_HOP_COUNT:-1}
      - RELAY_IGNORE_DIRECT=${RELAY_IGNORE_DIRECT:-false}
      - RELAY_REGION=${BAND:-eu868}
      #- RELAY_FREQUENCIES=868100000,868300000,868500000
      - RELAY_TX_POWER=${RELAY_TX_POWER:-16}
      - RELAY_MODULATION=${RELAY_MODULATION:-LORA}
      - RELAY_SF=${RELAY_SF:-7}
      - RELAY_BANDWIDTH=${RELAY_BANDWIDTH:-125000}
      - RELAY_CODERATE=${RELAY_CODERATE:-4/5}
      - RELAY_FSK_BITRATE=${RELAY_FSK_BITRATE:-0}
      - RELAY_SOCKET_DEVICES="concentratord"
      - RELAY_SOCKET_RELAY="concentratord"
      - RELAY_SOCKET_FORWARDER="forwarder"
