version: "3"

# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:

  chirpstack-concentratord:
    container_name: chirpstack-concentratord-${BAND:-eu868}
    image: xoseperez/chirpstack-concentratord:latest
    restart: unless-stopped
    volumes:
      - /tmp:/tmp
    devices:
      - /dev/spidev0.0
      - /dev/gpiochip0
      - /dev/gpiomem
    user: "${PUID:-1000}:${PGID:-1000}"
    group_add: 
      - ${PGID_GPIO:-997}
      - ${PGID_I2C:-998}
      - ${PGID_SPI:-999}
    environment:
      - DEBUG=INFO
      - MODEL=${MODEL:-RAK5146}
      #- INTERFACE=${INTERFACE:-SPI}
      #- RESET_GPIO=${RESET_GPIO:-17}
      #- POWER_EN_GPIO=${POWER_EN_GPIO:-0}
      #- HAS_GPS=${HAS_GPS:-0}
      - REGION=${BAND:-eu868}
      #- CHANNELS=${CHANNELS:-eu868}
      - SOCKET_NAME=${SOCKET_NAME:-concentratord}
