# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:

  chirpstack-mqtt-forwarder:
    container_name: chirpstack-mqtt-forwarder
    image: xoseperez/chirpstack-mqtt-forwarder:latest
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    volumes:
      - chirpstack-certificates:/etc/chirpstack-mqtt-forwader/certs
      - /tmp:/tmp
    environment:

      - LOGGING_LEVEL=INFO
      #- MQTT_TOPIC_PREFIX=${BAND:-eu868}
      - MQTT_SERVER=tcp://mosquitto:1883
      #- MQTT_USERNAME=""
      #- MQTT_PASSWORD=""
      #- MQTT_QOS=0
      #- MQTT_CA_CERT_PATH="/run/secrets/ca.pem"
      #- MQTT_CLIENT_CERT_PATH="/run/secrets/cert.pem"
      #- MQTT_CLIENT_KEY_PATH="/run/secrets/key.pem"
      #- MQTT_JSON="false"
      #- BACKEND="concentratord"
      #- BACKEND_SOCKET_NAME="concentratord"
      #- BACKEND_UDP_BIND="0.0.0.0:1700"
      #- BACKEND_FILTER_DEVADDR=""
      #- BACKEND_FILTER_JOINEUI=""
      - MQTT__TLS_CERT=/etc/chirpstack-mqtt-forwarder/certs/chirpstack-mqtt-forwarder/mqtt-broker/mqtt-broker.pem
      - MQTT__TLS_KEY=/etc/chirpstack-mqtt-forwarder/certs/chirpstack-mqtt-forwarder/mqtt-broker/mqtt-broker-key.pem
      - MQTT__CA_CERT=/etc/chirpstack-mqtt-forwarder/certs/ca/ca.pem
      - BACKEND__ENABLED=concentratord
      - BACKEND__CONCENTRATORD__EVENT_URL=ipc:///tmp/concentratord_event
      - BACKEND__CONCENTRATORD__COMMAND_URL=ipc:///tmp/concentratord_command

#secrets:
#  ca.pem:
#    file: ca.pem
#  cert.pem:
#    file: cert.pem
#  key.pem:
#    file: key.pem 

volumes:
  chirpstack-certificates:
