version: "3"

# ---------------------------------------------------------------------------
# SERVICES
# ---------------------------------------------------------------------------

services:

  # ---------------------------------------------------------------------------
  # Local concentratord service
  # ---------------------------------------------------------------------------

  chirpstack-mqtt-forwarder:
    container_name: chirpstack-mqtt-forwarder
    image: chirpstack-mqtt-forwarder:latest
    build:
      context: chirpstack-mqtt-forwarder-docker
      args:
        ARCH: ${ARCH:-arm64}
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack-mqtt-forwarder:/etc/chirpstack-mqtt-forwarder
      - chirpstack-certificates:/etc/chirpstack-mqtt-forwader/certs
      - /tmp:/tmp
    environment:
      - MQTT__TOPIC_PREFI=${BAND:-eu868}
      - MQTT__SERVER=tcp://127.0.0.1:1883
      - MQTT__USERNAME=
      - MQTT__PASSWORD=
      - MQTT__TLS_CERT=/etc/chirpstack-mqtt-forwarder/certs/chirpstack-mqtt-forwarder/mqtt-broker/mqtt-broker.pem
      - MQTT__TLS_KEY=/etc/chirpstack-mqtt-forwarder/certs/chirpstack-mqtt-forwarder/mqtt-broker/mqtt-broker-key.pem
      - MQTT__CA_CERT=/etc/chirpstack-mqtt-forwarder/certs/ca/ca.pem
      - BACKEND__ENABLED=concentratord
      - BACKEND__CONCENTRATORD__EVENT_URL=ipc:///tmp/concentratord_${BAND:-eu868}_event # See SOCKET_PREFIX in chirpstack-concentratord service
      - BACKEND__CONCENTRATORD__COMMAND_URL=ipc:///tmp/concentratord_${BAND:-eu868}_command # See SOCKET_PREFIX in chirpstack-concentratord service

volumes:
  chirpstack-certificates:
