version: '3'

services:

  chirpstack-mqtt-forwarder:
    
    # use pre-defined image
    image: chirpstack-mqtt-forwarder:latest

    # or comment out image: and build it yourself / with balena services
    build:
      context: .
      args:
        ARCH: amd64

    container_name: chirpstack-mqtt-forwarder
    restart: unless-stopped
    environment:
      - MQTT__TOPIC_PREFI=${BAND:-eu868}
      - MQTT__SERVER=tcp://127.0.0.1:1883
      - MQTT__USERNAME=
      - MQTT__PASSWORD=
      - MQTT__TLS_CERT=/etc/chirpstack-mqtt-forwarder/certs/chirpstack-mqtt-forwarder/mqtt-broker/mqtt-broker.pem
      - MQTT__TLS_KEY=/etc/chirpstack-mqtt-forwarder/certs/chirpstack-mqtt-forwarder/mqtt-broker/mqtt-broker-key.pem
      - MQTT__CA_CERT=/etc/chirpstack-mqtt-forwarder/certs/ca/ca.pem
      - BACKEND__ENABLED=semtech_udp
      #- BACKEND__CONCENTRATORD__EVENT_URL=ipc:///tmp/concentratord_${BAND:-eu868}_event # See SOCKET_PREFIX in chirpstack-concentratord service
      #- BACKEND__CONCENTRATORD__COMMAND_URL=ipc:///tmp/concentratord_${BAND:-eu868}_command # See SOCKET_PREFIX in chirpstack-concentratord service
