services:

  chirpstack-certificates:
    container_name: chirpstack-certificates
    build: 
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./certs:/chirpstack-certificates/certs
    environment:
      - CHIRPSTACK_GATEWAY_BRIDGE_HOSTS=127.0.0.1,localhost
      - MQTT_BROKER_HOSTS=127.0.0.1,localhost
    command: make