version: '3'

services:

  chirpstack-concentratord:
    
    # use pre-defined image
    image: chirpstack-concentratord:latest

    # or comment out image: and build it yourself / with balena services
    build:
      context: .
      args:
        ARCH: amd64

    container_name: chirpstack-concentratord
    restart: unless-stopped
    privileged: true
    ipc: host
    network_mode: host      # required to read main interface MAC instead of virtual one, only for sx1301 based concentrators
                            # you don't need this if you set the GATEWAY_EUI manually
    volumes:
      - /tmp:/tmp
    
    group_add:
      - "dialout"           # provides permissions to access USB concentrators

    environment:

      # Select the concentrator model (required, either RAK or chirpstack-concentratord naming)
      MODEL: "RAK5148"

      # Select the region (not needed for 2G4 concentrators, defaults to EU868 for the rest)
      #REGION: "EU868"

      # Select the channels (some regions have more than one channel set)
      #CHANNELS: "US915_0"

      # Set concentratord debug level (TRACE, DEBUG, INFO*, WARN, ERROR, OFF)
      #DEBUG: "INFO"
